#!/bin/bash
IFS=$'\n\t'

# bash_sessions - Session manager for the Bash shell
#
# Copyright (C) 2016 Alessandro Grassi <alessandro.g89@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

BASH_SESSIONS_DIR="$HOME/.bash_sessions"
BASH_SESSIONS_TEMP_DIR="/tmp/.bash_sessions/"
BASH_SESSIONS_MAXIMUM_OUTPUT_LINES="1000"


__bs_savepwd(){
	# check that we are inside a session
	[ -z "$BASH_SESSION_NAME" ] && return
	
	# check that the target directory exists
	[ -d "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}" ] || return
	
	# save current working directory to a file
	if [ "$PWD" != "$PREV_PWD" ]; then
		PREV_PWD="$PWD"
		echo "$PWD" > "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/pwd"
	fi
}

# save changes to the environment
__bs_saveenv(){
	# check that we are inside a session
	[ -z "$BASH_SESSION_NAME" ] && return
	
	# check that the target directory exists
	[ -d "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}" ] || return
	
	# check that temp dir exists
	[ -d "${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}" ] || mkdir -p "${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}"
	
	# save changes to the environment in a file
	cat "/proc/$$/environ" | tr '\0' '\n' | sort | grep "=" > "${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/initial_env"
	env | sort | grep "=" > "${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/current_env"
	diff --new-line-format=%L --old-line-format= --unchanged-line-format= \
		"${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/initial_env" \
		"${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/current_env" \
		| egrep -v "(PROMPT_COMMAND|SHLVL|COMP_WORDBREAKS)" > "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_changed"
	diff --new-line-format= --old-line-format=%L --unchanged-line-format= \
		"${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/initial_env" \
		"${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/current_env" \
		| egrep -v "(PATH|SHLVL|COMP_WORDBREAKS)" | cut -d = -f 1 > "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_deleted"
}

# create and activate a new session
n (){
	# check number of arguments
	if [ "$#" -ne 1 ]; then
		echo "Error: ${FUNCNAME[0]}() requires exactly 1 argument"
		return
	fi
	
	# check session not existing already
	if [ -d "${BASH_SESSIONS_DIR}/$1" ]; then
		echo "Error: session \"$1\" already exists"
		return
	fi
	
	# quit current session, if any
	[ -n "$BASH_SESSION_NAME" ] && c
	
	[ -d "${BASH_SESSIONS_DIR}" ] || mkdir "${BASH_SESSIONS_DIR}"
	[ -d "${BASH_SESSIONS_DIR}/$1" ] || mkdir "${BASH_SESSIONS_DIR}/$1"
	o "$1"
}

# activate an existing session
o (){
	# check number of arguments
	if [ "$#" -ne 1 ]; then
		echo "Error: ${FUNCNAME[0]}() requires exactly 1 argument"
		return
	fi
	
	# check that session exists
	if ! [ -d "${BASH_SESSIONS_DIR}/$1" ]; then
		echo "Error: session \"$1\" does not exist"
		return
	fi
	
	# quit current session, if any
	[ -n "$BASH_SESSION_NAME" ] && c
	
	# check that the session is not already in use
	if lsof "${BASH_SESSIONS_DIR}/$1/output" &> /dev/null; then
		echo "Error: session \"$1\" is already in use!"
		return
	fi
	
	# check that temp dir exists
	[ -d "${BASH_SESSIONS_TEMP_DIR}/${1}" ] || mkdir -p "${BASH_SESSIONS_TEMP_DIR}/${1}"
	
	# save existing environment
	env | sort | egrep -v "PROMPT_COMMAND|COMP_WORDBREAKS" | grep "=" >"${BASH_SESSIONS_TEMP_DIR}/${1}/previous_env"
	
	# set session name
	export BASH_SESSION_NAME="${1}"
	
	# switch to dedicated history file
	OLD_HISTFILE="$HISTFILE"
	echo "#$(date +%s)" >> "$OLD_HISTFILE"
	echo "o $1" >> "$OLD_HISTFILE"
	history -c
	HISTFILE="${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/history"
	history -r
	
	# add newline to output if needed
	[ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/loaded" ] && echo >> "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output"
	
	# switch to working directory
	OLD_PWD="$PWD"
	[ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/pwd" ] && cd "$(cat "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/pwd")"
	
	# load old output from file
	if [ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output" ]; then
		if [ $(wc -l "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output" | cut -f 1 -d " ") -ge ${BASH_SESSIONS_MAXIMUM_OUTPUT_LINES} ]; then
			tail -n ${BASH_SESSIONS_MAXIMUM_OUTPUT_LINES} "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output" > "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output.tail"
			mv "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output.tail" "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output"
		fi
		cat "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output"
	fi
	
	# save output to file
	OLD_PTS="$(readlink /proc/$$/fd/1)"
	exec &> >(tee -i -a "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output")
	
	# mark session as loaded
	touch "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/loaded"
	
	# set prompt command to save working directory
	OLD_PROMPT_COMMAND="${PROMPT_COMMAND}"
	PROMPT_COMMAND="${OLD_PROMPT_COMMAND}; __bs_savepwd;__bs_saveenv"
	
	# restore environment
	[ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_changed" ] && while read line; do
		export "$line";
	done < "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_changed"
	[ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_deleted" ] && while read line; do
		unset "$line";
	done < "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_deleted"
}

# exit active session
c (){
	# check number of arguments
	if [ "$#" -ne 0 ]; then
		echo "Error: ${FUNCNAME[0]}() does not accept arguments"
		return
	fi
	
	# check that we are in a session
	if [ -z "$BASH_SESSION_NAME" ]; then
		echo "No session active!"
		return
	fi
	
	# revert to old history file
	# FIXME: history -c here may cause a "bus error", not sure why
	#history -c
	HISTFILE="$OLD_HISTFILE"
	unset OLD_HISTFILE
	history -r
	
	# stop saving output to file
	exec &> "${OLD_PTS}"
	unset OLD_PTS
	
	# limit the length of saved output
	if [ $(wc -l "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output" | cut -f 1 -d " ") -ge ${BASH_SESSIONS_MAXIMUM_OUTPUT_LINES} ]; then
		tail -n ${BASH_SESSIONS_MAXIMUM_OUTPUT_LINES} "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output" > "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output.tail"
		mv "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output.tail" "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output"
	fi
	
	# revert to old working directory
	cd "$OLD_PWD"
	unset OLD_PWD
	
	# restore previous environment
	while read line; do
		export "$line";
	done < "${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/previous_env"
	env | sort | grep "=" > "${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/current_env"
	diff --new-line-format= --old-line-format=%L --unchanged-line-format= \
		"${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/current_env" \
		"${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/previous_env" \
		| grep "=" | cut -d = -f 1 | egrep -v "HISTFILE|BASH_SESSION_NAME" > "${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/env_deleted"
	while read line; do
		unset "$line";
	done < "${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/env_deleted"
	rm -f "${BASH_SESSIONS_TEMP_DIR}/${BASH_SESSION_NAME}/"*
	
	# revert to old prompt command
	PROMPT_COMMAND="${OLD_PROMPT_COMMAND}"
	unset OLD_PROMPT_COMMAND
	
	# mark session as unloaded
	[ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/loaded" ] && rm -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/loaded"
	unset BASH_SESSION_NAME

}

# delete an existing session
f (){
	# check number of arguments
	if [ "$#" -ne 1 ]; then
		echo "Error: ${FUNCNAME[0]}() requires exactly 1 argument"
		return
	fi
	
	# check that we are not in a session
	if [ -n "$BASH_SESSION_NAME" ]; then
		echo "Exit current session first!"
		return
	fi
	
	# check if session exists
	if ! [ -d "${BASH_SESSIONS_DIR}/$1" ]; then
		echo "Session \"$1\" does not exist!"
		return
	fi
	
	# ask confirmation and delete session
	read -p "Delete session \"$1\"? [yN] " -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		rm -f -r "${BASH_SESSIONS_DIR}/$1"
		echo "Session \"$1\" deleted"
	fi
}

# rename an existing session
r (){
	# check number of arguments
	if [ "$#" -ne 2 ]; then
		echo "Error: ${FUNCNAME[0]}() requires exactly 2 arguments"
		return
	fi
	
	# check that we are not in a session
	if [ -n "$BASH_SESSION_NAME" ]; then
		echo "Exit current session first!"
		return
	fi
	
	# check if session exists
	if ! [ -d "${BASH_SESSIONS_DIR}/$1" ]; then
		echo "Session \"$1\" does not exist!"
		return
	fi
	
	mv "${BASH_SESSIONS_DIR}/$1" "${BASH_SESSIONS_DIR}/$2"
	echo "Session \"$1\" renamed to \"$2\""
}

# re-open all session which were not explicitly closed
a (){
	for SESSION_NAME in $(ls "${BASH_SESSIONS_DIR}"); do
		if [ -f "${BASH_SESSIONS_DIR}/${SESSION_NAME}/loaded" ]; then
			if ! lsof "${BASH_SESSIONS_DIR}/${SESSION_NAME}/output"; then
				echo "Loading session \"${SESSION_NAME}\""
				
				local temp_rc_file="/tmp/.bash_session_rc_${SESSION_NAME}"
				local temp_desktop_file="$HOME/.local/share/applications/bash-session-${SESSION_NAME}.desktop"
				
				echo ". ~/.bashrc" > "${temp_rc_file}"
				echo "o ${SESSION_NAME}" >> "${temp_rc_file}"
				echo "rm -f \"${temp_rc_file}\"" >> "${temp_rc_file}"
				echo "rm -f \"${temp_desktop_file}\"" >> "${temp_rc_file}"
				
				echo "[Desktop Entry]" > "${temp_desktop_file}"
				echo "Exec=x-terminal-emulator -x bash --rcfile ${temp_rc_file}" >> "${temp_desktop_file}"
				echo "Type=Application" >> "${temp_desktop_file}"
				
				gtk-launch "bash-session-${SESSION_NAME}.desktop"
				sleep 0.1
			fi
		fi
	done
}

# print label for bash prompt
__bs_ps1 (){
	if [ -n "$BASH_SESSION_NAME" ]; then
		echo "[$BASH_SESSION_NAME]"
	else
		echo ""
	fi
}

# list sessions
function e {
	for i in $(ls ${BASH_SESSIONS_DIR}); do
		if [ -f "${BASH_SESSIONS_DIR}/${i}/loaded" ]; then
			if lsof "${BASH_SESSIONS_DIR}/${i}/output" &>/dev/null; then
				echo "${i}*"
			else
				echo "${i}+"
			fi
		else
			echo "${i}"
		fi;
	done
}

# helper function for completion
function __bs_comp_list {
	ls "${BASH_SESSIONS_DIR}"
}

# completion command
function _bash_session_comp {
	local curw
	COMPREPLY=()
	curw=${COMP_WORDS[COMP_CWORD]}
	COMPREPLY=($(compgen -W '`__bs_comp_list`' -- $curw))
	return 0
}


# bind completion command for o, f, r to _comp
shopt -s progcomp
complete -o filenames -F _bash_session_comp o
complete -o filenames -F _bash_session_comp f
complete -o filenames -F _bash_session_comp r

